CREATE TABLE dives (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    dive_date DATE NOT NULL,
    country TEXT NOT NULL,
    region TEXT NOT NULL,
    dive_site TEXT NOT NULL,
    max_depth INTEGER,
    duration INTEGER,
    water_temp INTEGER,
    dive_shop TEXT,
    guide TEXT,
    buddy TEXT,
    viz INTEGER,
    dive_type TEXT,
    drift_dive BOOLEAN,
    night_dive BOOLEAN,
    description TEXT,
    animals_spotted INTEGER [],
    rating INTEGER NOT NULL
);